### ISSUE TITLE
Quake 3 bsp support

### ISSUE THREAD

**Issue by LordGrievous** [andyp123/blender_io_mesh_bsp#14]
Hi, I asked this on Discord a few months ago but maybe this is a better place :)

Could you add import support for Quake 3 bsp files, this would include patch meshes if course.

This would be a dream come true for me, I would rather map in Trenchbroom and compile to bsp, then import this into Blender and save to another format like .obj or .fbx for use in Unreal engine.

I love UE4 but the level tools are shit, and I'm not good enough to create my entire levels in Blender :(

Thanks for the work you've done so far though!

EDIT: If it is possible to also properly import the Q3 textures (not shaders) into Blender, that would be even better :)

**Comment by andyp123** [comment]
Sorry, I don't really want to spend much more time on this, so Quake 3 bsp support is a definite no.
