### ISSUE TITLE
Half-Life 1 bsp support

### ISSUE THREAD

**Issue by LordGrievous** [andyp123/blender_io_mesh_bsp#15]
Seeing how HL1 is based of a heavily modified Q1 engine, I think that the bsp format isn't that much different either.

Could you add HL1 (GoldSource) bsp support?

This certainly isn't a pressing issue, but it would be helpful since I also do a lot of HL1 mapping :)

**Comment by andyp123** [comment]
Not 100% sure, but I recall testing a couple of old HL1 levels with an old version of the addon. No idea if that still works, but I can investigate. If I get it working, it probably will only import geometry.

**Comment by Stalker2106** [comment]
i made a fork exactly for this purpose: https://github.com/stalker2106x/blender_io_mesh_bsp/

**Comment by andyp123** [comment]
Awesome! I'm going to close this issue and recommend people wanting proper HL support to use your fork.
