### ISSUE TITLE
Quake 2 bsp support

### ISSUE THREAD

**Issue by LordGrievous** [andyp123/blender_io_mesh_bsp#16]
Would also come in handy with all the Q2 maps I've got lying around :)

Don't know how much work this would require, only difference I know of is that textures aren't saved in the bsp.

**Comment by andyp123** [comment]
I've not looked into this at all, but from what I remember, Quake 2 also stores some extra data about all surfaces in the map, so this would require some extra coding to get working and is much less trivial than Half-Life or Hexen 2 support. Closing because I will probably never add it.
