### ISSUE TITLE
v0.0.8 for Blender 2.80

### ISSUE THREAD

**Issue by archienz** [andyp123/blender_io_mesh_bsp#2]
Downloaded from your releases page, 

however when checking in blender 2.80
![beta](https://user-images.githubusercontent.com/240870/50763860-229bbd80-12c5-11e9-9e24-3116c6e6831c.png)

I downloaded 2.80 beta as you instructed.

**Comment by andyp123** [comment]
Really sorry. I don't know how I managed to mess that up. I've replaced the link with the link to the new v0.0.9 release, which has some new features. You can get it [here](https://github.com/andyp123/blender_io_mesh_bsp/releases/download/v0.0.9/io_mesh_bsp_v009.zip)

**Comment by archienz** [comment]
Thanks for being a champ and fixing that mate :)
