### ISSUE TITLE
Trouble importing Aerowalk

### ISSUE THREAD

**Issue by mhomde** [andyp123/blender_io_mesh_bsp#20]
![aerowalk](https://user-images.githubusercontent.com/10740939/88468150-a3d69780-cedf-11ea-90c0-0255c2d4db00.png)

Amazing add-on! This is a stab in the dark I know, and I completely understand if it's not fixable.

Anyhoo, trying to import one of my old levels, Aerowalk  (http://bigfoot.quake1.net/maps/aerowalk.bsp)  but get an error (see attachment.  Would be beyond awesome if there was an easy fix. Maybe I can just disable the texture import or something?

Cheers
/Preacher

**Comment by MattTree** [comment]
I'm getting the same error but for a CS:GO map.

**Comment by MattTree** [comment]
https://github.com/andyp123/blender_io_mesh_bsp/issues/17

**Comment by amir22gm** [comment]
i get this error too`who can fix it?`

**Comment by andyp123** [comment]
Wow, the author of one of the most famous Quake DM maps himself! Hi, Preacher! Sorry for the insanely long reply delay. I didn't notice that an issue had been reported for some reason - usually I get an email.

This looks like it shouldn't be too difficult to fix, actually, but I'm not really set up for doing it right now. Looks like I'm bad at fault tolerance, as it appears that there is simply a null texture name that is breaking it. I thought I had fixed this ages ago.

In the mean time, if you haven't managed to find a way to get Aerowalk into Blender, you can get it to import without textures by disabling "create materials" in the importer options.

If I fix this, I'll update and close the issue.

**Comment by andyp123** [comment]
Finally got around to doing a small update to this addon. Sorry it took so long, but I can now import Aerowalk without any issues.
