### ISSUE TITLE
will .wad supported?

### ISSUE THREAD

**Issue by boutoron2685** [andyp123/blender_io_mesh_bsp#22]
As you know, .wad is texture bundle file(for quake, goldSrc, ect...).
It seems that it is not yet supported. The texture did not load even if it was in a directory same as .bsp.
Do you have plans to support?

**Comment by motorsep** [comment]
Doesn't .bsp contain all the textures needed for the said .bsp ? Wad is only needed for when you build your maps in level editors. Once .bsp is compiled from .map, textures are embedded into .bsp.

**Comment by Stalker2106** [comment]
i made a fork exactly for this purpose: https://github.com/stalker2106x/blender_io_mesh_bsp/
it expects you to unpack the wad to a folder, and provide the folder path when importing

**Comment by boutoron2685** [comment]
> i made a fork exactly for this purpose: https://github.com/stalker2106x/blender_io_mesh_bsp/ it expects you to unpack the wad to a folder, and provide the folder path when importing
![screen](https://user-images.githubusercontent.com/16276011/142362395-f7d2df0a-dcb4-4273-a03d-872cad2e040e.png)


oh, it works thanks!
