### ISSUE TITLE
I want to import a map of APEX, but when I try to import it, I get an error like this

### ISSUE THREAD

**Issue by AsutoraGG** [andyp123/blender_io_mesh_bsp#24]
![image](https://user-images.githubusercontent.com/76235964/126481954-30057f56-d9f0-45a8-86b5-3a05450cb5c9.png)
hmm...

**Comment by itsdikey** [comment]
having the same issue with 13dawn

**Comment by AsutoraGG** [comment]
APEX Map cannot be imported with this

**Comment by andyp123** [comment]
Apex Legends? This is for the 1996 game Quake's bsp levels only, sorry.
