### ISSUE TITLE
The texture is not imported and when I select the "creat materials" option, the import will report an error.

### ISSUE THREAD

**Issue by renjianfeng** [andyp123/blender_io_mesh_bsp#7]
Sorry, English is not my native language, this is really great work.

![image](https://user-images.githubusercontent.com/19640483/57195518-3a8b0180-6f86-11e9-8a36-9c60ffbb19aa.png)
![image](https://user-images.githubusercontent.com/19640483/57195522-3eb71f00-6f86-11e9-897b-9d44d6fd8a78.png)

This is the BSP file:
[marsbase.zip](https://github.com/andyp123/blender_io_mesh_bsp/files/3145642/marsbase.zip)

**Comment by andyp123** [comment]
Thanks! There appears to have been a few important changes to the Blender API recently, and I need to fix the problems that have sprung up in this adon as a result of changes. The Blender python API will become stable in the next week, so I will update the addon once that happens.

**Comment by andyp123** [comment]
This is fixed now. Sorry it took so long to get to the problem and fix it. The latest version has a few improvements and imports levels much faster than before, so please check it out [here](https://github.com/andyp123/blender_io_mesh_qmap/releases).
